# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: maps_development
  host: localhost
  username: maps
  password: maps123

test:
  <<: *default
  database: maps_test
  host: localhost
  username: maps
  password: maps123

production:
  <<: *default
  host: ec2-54-221-249-3.compute-1.amazonaws.com
  database: d6hqhph7rdjp3o
  username: rtmzdgqtfueeuq
  password: 0msQ2fl1JqYq3eCPF7yZQ_Pgz3
