# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a0dac543debc53de90fe0f428d193d2bc1f92ab049b2d86dbb07d503450c27e9fa5951b3bf91c0bdc4bad972530f0204571a94ae4b1b145b43fab3ff975d3d4

test:
  secret_key_base: b093ad7e38cb9501222f6bfd82b8d38bdc77cc9e6b86aeac1b3ea18683f0881e4efab44e5af1f3ff39cd0b57aa987e558457d5c6a6929fba88e059ff385d8655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
